swagger: '2.0'
info:
  version: '1.0'
  title: audit
  description: 'TODO: Add Description'
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: example.com
basePath: /v1/audit
securityDefinitions:
  auth:
    type: oauth2
    flow: implicit
    authorizationUrl: http://example.com/v1/audit
    scopes: {}
    x-skip-client-authentication: false
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /history:
    post:
      description: ''
      summary: this will provide data audit history
      operationId: HistoryPost
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/ThisWillProvideDataAuditHistoryrequest'
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: X-msgid
        in: header
        required: true
        type: string
        description: ''
      - name: ts
        in: header
        required: true
        type: string
        description: ''
      - name: Authorization
        in: header
        required: true
        type: string
        description: ''
      - name: x-authenticated-user-token
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security:
      - auth: []
      x-unitTests:
      - request:
          method: POST
          uri: /history
          headers:
            Content-Type: application/json
            X-msgid: 8e27cbf5-e299-43b0-bca7-8347f7e5abcf
            ts: 2017-05-25 10:18:56:578+0530
            Authorization: Bearer {{api-key}}
            x-authenticated-user-token: '{{user-token}}'
          body: "{\r\n  \"id\": \"\",\r\n  \"ver\": \"3.0\",\r\n  \"ts\": \"YYYY-MM-DDThh:mm:ssZ+/-nn.nn\",\r\n  \"params\": {\r\n    \"did\": \"evice UUID from which API is called\", \r\n    \"key\": \" API key (dynamic)\",\r\n    \"msgid\": \"unique request message id, UUID\"\r\n  },\r\n  \"request\": { \r\n        \"filters\": {\r\n                \r\n               \"objectType\": [\"user\"],\r\n               \"toDate\" :\"2017-10-13\"\r\n                \r\n        }\r\n  }\r\n}"
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: this will provide data audit history
        x-testDescription: ''
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
definitions:
  ThisWillProvideDataAuditHistoryrequest:
    title: this will provide data audit historyRequest
    example:
      id: ''
      ver: 3.0
      ts: YYYY-MM-DDThh:mm:ssZ+/-nn.nn
      params:
        did: evice UUID from which API is called
        key: ' API key (dynamic)'
        msgid: unique request message id, UUID
      request:
        filters:
          objectType:
          - user
          toDate: 2017-10-13
    type: object
    properties:
      id:
        description: ''
        type: string
      ver:
        description: ''
        example: 3.0
        type: string
      ts:
        description: ''
        example: YYYY-MM-DDThh:mm:ssZ+/-nn.nn
        type: string
      params:
        $ref: '#/definitions/Params'
        example:
          did: evice UUID from which API is called
          key: ' API key (dynamic)'
          msgid: unique request message id, UUID
      request:
        $ref: '#/definitions/Request'
        example:
          filters:
            objectType:
            - user
            toDate: 2017-10-13
    required:
    - id
    - ver
    - ts
    - params
    - request
  Params:
    title: Params
    example:
      did: evice UUID from which API is called
      key: ' API key (dynamic)'
      msgid: unique request message id, UUID
    type: object
    properties:
      did:
        description: ''
        example: evice UUID from which API is called
        type: string
      key:
        description: ''
        example: ' API key (dynamic)'
        type: string
      msgid:
        description: ''
        example: unique request message id, UUID
        type: string
    required:
    - did
    - key
    - msgid
  Request:
    title: Request
    example:
      filters:
        objectType:
        - user
        toDate: 2017-10-13
    type: object
    properties:
      filters:
        $ref: '#/definitions/Filters'
        example:
          objectType:
          - user
          toDate: 2017-10-13
    required:
    - filters
  Filters:
    title: Filters
    example:
      objectType:
      - user
      toDate: 2017-10-13
    type: object
    properties:
      objectType:
        description: ''
        example:
        - user
        type: array
        items:
          type: string
      toDate:
        description: ''
        example: 2017-10-13
        type: string
    required:
    - objectType
    - toDate
