swagger: '2.0'
info:
  version: '1.0'
  title: getUserCount
  description: 'TODO: Add Description'
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: example.com
basePath: /data/v1/notification
securityDefinitions:
  auth:
    type: oauth2
    flow: implicit
    authorizationUrl: http://example.com/data/v1/notification
    scopes: {}
    x-skip-client-authentication: false
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /audience:
    post:
      description: ''
      summary: get the audience count for a locations
      operationId: AudiencePost
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/GetTheAudienceCountForALocationsrequest'
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: id
        in: header
        required: true
        type: string
        description: ''
      - name: X-msgid
        in: header
        required: true
        type: string
        description: ''
      - name: ts
        in: header
        required: true
        type: string
        description: ''
      - name: Authorization
        in: header
        required: true
        type: string
        description: ''
      - name: x-authenticated-user-token
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security:
      - auth: []
      x-unitTests:
      - request:
          method: POST
          uri: /audience
          headers:
            Content-Type: application/json
            id: id
            X-msgid: 8e27cbf5-e299-43b0-bca7-8347f7e5abcf
            ts: 2017-05-25 10:18:56:578+0530
            Authorization: Bearer {{api-key}}
            x-authenticated-user-token: '{{user-token}}'
          body: "\r\n{\r\n \"params\": { },\r\n    \"request\":{\r\n         \"locationIds\" : [\"123\",\"456\"],\r\n         \"userListReq\" : false,\r\n         \"estimatedCountReq\" : false\r\n   }\r\n}  "
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: get the audience count for a locations
        x-testDescription: ''
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
definitions:
  GetTheAudienceCountForALocationsrequest:
    title: get the audience count for a locationsRequest
    example:
      params: {}
      request:
        locationIds:
        - 123
        - 456
        userListReq: false
        estimatedCountReq: false
    type: object
    properties:
      params:
        description: ''
        example: {}
        type: object
      request:
        $ref: '#/definitions/Request'
        example:
          locationIds:
          - 123
          - 456
          userListReq: false
          estimatedCountReq: false
    required:
    - params
    - request
  Request:
    title: Request
    example:
      locationIds:
      - 123
      - 456
      userListReq: false
      estimatedCountReq: false
    type: object
    properties:
      locationIds:
        description: ''
        example:
        - 123
        - 456
        type: array
        items:
          type: string
      userListReq:
        description: ''
        example: false
        type: boolean
      estimatedCountReq:
        description: ''
        example: false
        type: boolean
    required:
    - locationIds
    - userListReq
    - estimatedCountReq
