swagger: '2.0'
info:
  version: '1.0'
  title: Badges
  description: 'TODO: Add Description'
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: example.com
basePath: /
securityDefinitions:
  auth:
    type: oauth2
    flow: implicit
    authorizationUrl: http://example.com
    scopes: {}
    x-skip-client-authentication: false
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /v1/badges/list:
    get:
      description: ''
      summary: provides list of badges
      operationId: V1BadgesListGet
      produces:
      - application/json
      parameters:
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: ts
        in: header
        required: true
        type: string
        description: ''
      - name: X-msgid
        in: header
        required: true
        type: string
        description: ''
      - name: x-authenticated-user-token
        in: header
        required: true
        type: string
        description: ''
      - name: Authorization
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security:
      - auth: []
      x-unitTests:
      - request:
          method: GET
          uri: /v1/badges/list
          headers:
            Content-Type: application/json
            ts: 2017-05-25 10:18:56:578+0530
            X-msgid: 8e27cbf5-e299-43b0-bca7-8347f7e5abcf
            x-authenticated-user-token: '{{user-token}}'
            Authorization: Bearer {{api-key}}
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: provides list of badges
        x-testDescription: ''
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /user/v1/badges/add:
    post:
      description: add badge to user
      summary: add badges to user
      operationId: UserV1BadgesAddPost
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/AddBadgesToUserrequest'
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: ts
        in: header
        required: true
        type: string
        description: ''
      - name: X-msgid
        in: header
        required: true
        type: string
        description: ''
      - name: x-authenticated-user-token
        in: header
        required: true
        type: string
        description: ''
      - name: Authorization
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security:
      - auth: []
      x-unitTests:
      - request:
          method: POST
          uri: /user/v1/badges/add
          headers:
            Content-Type: application/json
            ts: 2017-05-25 10:18:56:578+0530
            X-msgid: 8e27cbf5-e299-43b0-bca7-8347f7e5abcf
            x-authenticated-user-token: '{{user-token}}'
            Authorization: Bearer {{api-key}}
          body: "{\r\n \"params\": { },\r\n    \"request\":{                 \r\n      \"badgeTypeId\": \"0123206539020943360\",\r\n    \"receiverId\" :\"96d2f097-3f82-4d83-97de-79a58356a254\"\r\n      \r\n    }\r\n } "
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: add badges to user
        x-testDescription: add badge to user
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
definitions:
  AddBadgesToUserrequest:
    title: add badges to userRequest
    example:
      params: {}
      request:
        badgeTypeId: 0123206539020943360
        receiverId: 96d2f097-3f82-4d83-97de-79a58356a254
    type: object
    properties:
      params:
        description: ''
        example: {}
        type: object
      request:
        $ref: '#/definitions/Request'
        example:
          badgeTypeId: 0123206539020943360
          receiverId: 96d2f097-3f82-4d83-97de-79a58356a254
    required:
    - params
    - request
  Request:
    title: Request
    example:
      badgeTypeId: 0123206539020943360
      receiverId: 96d2f097-3f82-4d83-97de-79a58356a254
    type: object
    properties:
      badgeTypeId:
        description: ''
        example: 0123206539020943360
        type: string
      receiverId:
        description: ''
        example: 96d2f097-3f82-4d83-97de-79a58356a254
        type: string
    required:
    - badgeTypeId
    - receiverId
