swagger: '2.0'
info:
  version: '1.0'
  title: GEO LOCATION
  description: 'TODO: Add Description'
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: example.com
basePath: /
securityDefinitions:
  auth:
    type: oauth2
    flow: implicit
    authorizationUrl: http://example.com
    scopes: {}
    x-skip-client-authentication: false
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /org/v1/location/create:
    post:
      description: ''
      summary: Create Location
      operationId: OrgV1LocationCreatePost
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/CreateLocationrequest'
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: ts
        in: header
        required: true
        type: string
        description: ''
      - name: X-msgid
        in: header
        required: true
        type: string
        description: ''
      - name: Authorization
        in: header
        required: true
        type: string
        description: ''
      - name: x-authenticated-user-token
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security:
      - auth: []
      x-unitTests:
      - request:
          method: POST
          uri: /org/v1/location/create
          headers:
            Content-Type: application/json
            ts: 2017-05-25 10:18:56:578+0530
            X-msgid: 8e27cbf5-e299-43b0-bca7-8347f7e5abcf
            Authorization: Bearer {{api-key}}
            x-authenticated-user-token: '{{user-token}}'
          body: >2-
              {

            "request": {

              "rootOrgId": "0123668063921192960",

                   "data":[

                         {

                         "location":"name of location",

                         "type":"location type optional"

                        },

                        {

                         "location":"name of location",

                         "type":"location type optional"

                        }

                      ]

            }

            }
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Create Location
        x-testDescription: ''
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /v1/location/update/{locationId}:
    patch:
      description: ''
      summary: Update Geo Location
      operationId: V1LocationUpdateByLocationIdPatch
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/UpdateGeoLocationrequest'
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: ts
        in: header
        required: true
        type: string
        description: ''
      - name: X-msgid
        in: header
        required: true
        type: string
        description: ''
      - name: Authorization
        in: header
        required: true
        type: string
        description: ''
      - name: x-authenticated-user-token
        in: header
        required: true
        type: string
        description: ''
      - name: locationId
        in: path
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security:
      - auth: []
      x-unitTests: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /v1/location/delete/{locationId}:
    delete:
      description: ''
      summary: Delete Location
      operationId: V1LocationDelete0123667529089925122Delete
      produces:
      - application/json
      parameters:
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: ts
        in: header
        required: true
        type: string
        description: ''
      - name: X-msgid
        in: header
        required: true
        type: string
        description: ''
      - name: Authorization
        in: header
        required: true
        type: string
        description: ''
      - name: x-authenticated-user-token
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security:
      - auth: []
      x-unitTests:
      - request:
          method: DELETE
          uri: /v1/location/delete/0123667529089925122
          headers:
            Content-Type: application/json
            ts: 2017-05-25 10:18:56:578+0530
            X-msgid: 8e27cbf5-e299-43b0-bca7-8347f7e5abcf
            Authorization: Bearer {{api-key}}
            x-authenticated-user-token: '{{user-token}}'
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Delete Location
        x-testDescription: ''
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /org/v1/location/read/{locationId}:
    get:
      description: ''
      summary: Get Geo Location By Id
      operationId: OrgV1LocationRead01240144028287795224Get
      produces:
      - application/json
      parameters:
      - name: type
        in: query
        required: true
        type: string
        description: ''
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: ts
        in: header
        required: true
        type: string
        description: ''
      - name: X-msgid
        in: header
        required: true
        type: string
        description: ''
      - name: Authorization
        in: header
        required: true
        type: string
        description: ''
      - name: x-authenticated-user-token
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security:
      - auth: []
      x-unitTests:
      - request:
          method: GET
          uri: /org/v1/location/read/01240144028287795224?type=organisation
          headers:
            Content-Type: application/json
            ts: 2017-05-25 10:18:56:578+0530
            X-msgid: 8e27cbf5-e299-43b0-bca7-8347f7e5abcf
            Authorization: Bearer {{api-key}}
            x-authenticated-user-token: '{{user-token}}'
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Get Geo Location By Id
        x-testDescription: ''
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
definitions:
  CreateLocationrequest:
    title: Create LocationRequest
    example:
      request:
        rootOrgId: 0123668063921192960
        data:
        - location: name of location
          type: location type optional
        - location: name of location
          type: location type optional
    type: object
    properties:
      request:
        $ref: '#/definitions/Request'
        example:
          rootOrgId: 0123668063921192960
          data:
          - location: name of location
            type: location type optional
          - location: name of location
            type: location type optional
    required:
    - request
  Request:
    title: Request
    example:
      rootOrgId: 0123668063921192960
      data:
      - location: name of location
        type: location type optional
      - location: name of location
        type: location type optional
    type: object
    properties:
      rootOrgId:
        description: ''
        example: 0123668063921192960
        type: string
      data:
        description: ''
        example:
        - location: name of location
          type: location type optional
        - location: name of location
          type: location type optional
        type: array
        items:
          $ref: '#/definitions/Datum'
    required:
    - rootOrgId
    - data
  Datum:
    title: Datum
    example:
      location: name of location
      type: location type optional
    type: object
    properties:
      location:
        description: ''
        example: name of location
        type: string
      type:
        description: ''
        example: location type optional
        type: string
    required:
    - location
    - type
  UpdateGeoLocationrequest:
    title: Update Geo LocationRequest
    example:
      request:
        location: BANGALORE
        type: location type optional
    type: object
    properties:
      request:
        $ref: '#/definitions/Request4'
        example:
          location: BANGALORE
          type: location type optional
    required:
    - request
  Request4:
    title: Request4
    example:
      location: BANGALORE
      type: location type optional
    type: object
    properties:
      location:
        description: ''
        example: BANGALORE
        type: string
      type:
        description: ''
        example: location type optional
        type: string
    required:
    - location
    - type
