## This section has variables with empty values
## It is mandatory to provide values for these
## If you don't provide a value for these variables, the chart installation will not proceed

## The domain name or Public IP address
## The domain name should start with http or https
## For example https://example.com
domain: ""

## Can be one of - azure, aws, gcloud
sunbird_cloud_service_provider: ""

## Public Storage Bucket Details
sunbird_account_name: ""
sunbird_account_key: ""

## Private Storage Bucket Details
sunbird_analytics_blob_account_name: ""
sunbird_analytics_blob_account_key: ""


## This section has variables with empty values
## It is strongly recommended to provide values for these
## If you don't provide a value for these variables, they will default to empty values
## If these variables are empty, some features on the application might not work as expected 
google_captcha_mobile_private_key: ""
google_captcha_private_key: ""
sunbird_mail_server_from_email: ""
sunbird_mail_server_host: ""
sunbird_mail_server_password: ""
sunbird_mail_server_port: ""
sunbird_mail_server_username: ""
sunbird_msg_91_auth: ""
sunbird_msg_sender: ""
sunbird_url_shortner_access_token: ""
merge_domain: ""


## This section has variables with empty values
## If you provide a value to the variable, then that will take the highest precedence
## If you don't provide a value to the variable, then one of the following will occur
## - Auto generate the value for the variable
## - Fetch the value from another kubernetes configuration like secret or configmap
## For exact details on on the behavior, refer to the comments section above the variable
ekstep_authorization: ""
sunbird_authorization: ""
sunbird_encryption_key: ""
sunbird_keycloak_user_federation_provider_id: ""
sunbird_pg_user: ""
sunbird_pg_password: ""
sunbird_sso_publickey: ""
sunbird_sso_username: ""
sunbird_sso_password: ""
sunbird_sso_client_secret: ""
sunbird_sso_lb_ip: ""

## Storage bucket name where the contents are stores
sunbird_content_azure_storage_container: ""

## This section has variables with default values
## These are standard defaults that work well
## You can override these if you have a use case for it
ENV_NAME: dev
PORTAL_SERVICE_PORT: http://player.ed.svc.cluster.local:3000
SUNBIRD_KAFKA_URL: http://kafka.lern.svc.cluster.local:9092
accesstoken:
  publickey:
    basepath: /keys/
actor_hostname: actor-service
api_actor_provider: local
background_actor_provider: local
bind_hostname: 0.0.0.0
ekstep_api_base_url: http://learning.knowlg.svc.cluster.local:8080/learning-service
feed_limit: 30
form_api_endpoint: /plugin/v1/form/read
isMultiDCEnabled: false
kafka_urls: http://kafka.lern.svc.cluster.local:9092
learner_in_memory_cache_ttl: 600
notification_service_base_url: http://notification-service.lern.svc.cluster.local:9000
org_index_alias: org_alias
quartz_shadow_user_migration_timer: 0 0 1 1/1 * ? *
sunbird_analytics_api_base_url: http://analytics-service.obsrv.svc.cluster.local:9000
sunbird_api_base_url: http://knowledge-mw-service.knowlg.svc.cluster.local:5000
sunbird_api_mgr_base_url: http://knowledge-mw-service.knowlg.svc.cluster.local:5000
sunbird_app_name: sunbird
sunbird_cache_enable: true
sunbird_cassandra_consistency_level: local_quorum
sunbird_cassandra_host: http://cassandra.lern.svc.cluster.local
sunbird_cassandra_password: passwod
sunbird_cassandra_port: 9042
sunbird_cassandra_username: admin
sunbird_cert_service_base_url: http://cert-service.lern.svc.cluster.local:9000
sunbird_course_batch_notification_enabled: true
sunbird_course_batch_notification_signature: sunbird
sunbird_cs_base_url: http://knowledge-mw-service.knowlg.svc.cluster.local:5000
sunbird_cs_search_path: /v1/content/search
sunbird_default_channel: sunbird
sunbird_email_max_recipients_limit: 100
sunbird_encryption_mode: local
sunbird_env_logo_url: ""
sunbird_environment: dev
sunbird_es_host: http://elasticsearch.lern.svc.cluster.local
sunbird_es_port: 9300
sunbird_fuzzy_search_threshold: 0.5
sunbird_gzip_enable: true
sunbird_gzip_size_threshold: 262144
sunbird_health_check_enable: false
sunbird_installation: sunbird
sunbird_installation_display_name: sunbirddev
sunbird_installation_display_name_for_sms: sunbird
sunbird_installation_email: info@sunbird.org
sunbird_instance: sunbird
sunbird_keycloak_required_action_link_expiration_seconds: 2592000
sunbird_mw_system_host: learner-service
sunbird_mw_system_port: 8088
sunbird_open_saber_bridge_enable: false
sunbird_otp_allowed_attempt: 2
sunbird_otp_expiration: 1800
sunbird_otp_length: 6
sunbird_pg_db: quartz
sunbird_pg_host: postgresql.lern.svc.cluster.local
sunbird_pg_port: 5432
sunbird_quartz_mode: cluster
sunbird_redis_host: redis.lern.svc.cluster.local
sunbird_redis_port: 6379
sunbird_registry_service_baseurl: http://registry-service.registry.svc.cluster.local:8081/
sunbird_remote_bg_req_router_path: akka.tcp://SunbirdMWSystem@actor-service:8088/user/BackgroundRequestRouter
sunbird_remote_req_router_path: akka.tcp://SunbirdMWSystem@actor-service:8088/user/RequestRouter
sunbird_reset_pass_msg: 'You have requested to reset password. Click on the link to set a password: {0}'
sunbird_search_service_api_base_url: http://search-service.knowlg.svc.cluster.local:9000
sunbird_sso_client_id: lms
sunbird_sso_realm: sunbird
sunbird_telemetry_base_url: http://telemetry-service.obsrv.svc.cluster.local:9001
sunbird_time_zone: Asia/Kolkata
sunbird_url_shortner_enable: true
sunbird_user_bulk_upload_size: 1001
sunbird_user_cert_kafka_topic: cert
sunbird_user_profile_field_default_visibility: private
telemetry_pdata_id: learner
telemetry_pdata_pid: learner-service
telemetry_queue_threshold_value: 100
user_index_alias: user_alias


## Variables with empty values
## The value for these variables will be contstucted using other variables
## If you provide a value to the variable, then that will take the highest precedence
## It's recommended to leave these blanks unless you have a strong use case to override them
sunbird_sso_url: ""
sunbird_subdomain_keycloak_base_url: "merge + /auth/"
sunbird_web_url: ""


## Helper variables which are used to construct other variables
keycloak_auth_endpoint: "/auth/"
