version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202201-02
    # https://circleci.com/docs/parallelism-faster-jobs/
    # parallelism: 4
    # The resource_class feature allows configuring CPU and RAM resources for each job. Different resource classes are available for different executors. https://circleci.com/docs/2.0/configuration-reference/#resourceclass
    resource_class: large
    steps:
      - checkout
      - restore_cache:
          key: userorg-dependency-cache-{{ checksum "pom.xml" }}
      - run: mvn clean install -DCLOUD_STORE_GROUP_ID=$CLOUD_STORE_GROUP_ID -DCLOUD_STORE_ARTIFACT_ID=$CLOUD_STORE_ARTIFACT_ID -DCLOUD_STORE_VERSION=$CLOUD_STORE_VERSION
      - run: cd controller && mvn play2:dist
      - save_cache:
          key: userorg-dependency-cache-{{ checksum "pom.xml" }}
          paths: ~/.m2
      - run:
         name: Analyze on SonarCloud
         command: mvn verify -DskipTests sonar:sonar -Dsonar.projectKey=Sunbird-Lern_userorg-service -Dsonar.organization=sunbird-lern -Dsonar.host.url=https://sonarcloud.io -Dsonar.coverage.exclusions=**/cassandra-utils/**,**/es-utils/**,**/models/**,**/model/**,**/bean/**,**/dto/**,**/bulkupload/**,**/error/**,**/exception/**,**/util/search/** -Dsonar.coverage.jacoco.xmlReportPaths=/home/circleci/project/reports/target/jacoco/jacoco.xml

workflows:
  version: 2.1
  workflow:
    jobs:
      - build
