version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - restore_cache:
          key: lms-dependency-cache-{{ checksum "pom.xml" }}
      - run: mvn clean install
      - run: cd service && mvn play2:dist
      - save_cache:
          key: lms-dependency-cache-{{ checksum "pom.xml" }}
          paths: ~/.m2
      - run:
         name: Analyze on SonarCloud
         command: mvn verify -DskipTests sonar:sonar -Dsonar.projectKey=project-sunbird_sunbird-lms-service -Dsonar.organization=project-sunbird -Dsonar.host.url=https://sonarcloud.io -Dsonar.coverage.exclusions=**/models/**,**/bean/**,**/responsecode/** -Dsonar.coverage.jacoco.xmlReportPaths=/home/circleci/project/service/target/site/jacoco/jacoco.xml,/home/circleci/project/actors/sunbird-lms-mw/actors/user/target/site/jacoco/jacoco.xml,/home/circleci/project/actors/sunbird-lms-mw/actors/common/target/site/jacoco/jacoco.xml,/home/circleci/project/actors/sunbird-lms-mw/actors/sunbird-utils/auth-verifier/target/site/jacoco/jacoco.xml


workflows:
  version: 2.1
  workflow:
    jobs:
      - build
