swagger: '2.0'
info:
  version: '1.0'
  title: fcm
  description: 'TODO: Add Description'
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: example.com
basePath: /v1/notification
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /send:
    post:
      description: ''
      summary: fcm push
      operationId: SendPost
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/FcmPushrequest'
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Authorization
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security: []
      x-unitTests:
      - request:
          method: POST
          uri: /send
          headers:
            Content-Type: application/json
            Authorization: Bearer {{api-key}}
          body: >-
            {

            "request": {
                "to":"SunbirdNotif",
                "type":"fcm",
              "data": {
                  "title" : "Announcement!!",
                  "notifType" : "announcement",
                  "summary" : "New announcement from rootOrg",
                  "body" : "www.staging-sunbird.org/new/announcement"
              }
            }

            }
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: fcm push
        x-testDescription: ''
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
definitions:
  FcmPushrequest:
    title: fcm pushRequest
    example:
      request:
        to: SunbirdNotif
        type: fcm
        data:
          title: Announcement!!
          notifType: announcement
          summary: New announcement from rootOrg
          body: www.staging-sunbird.org/new/announcement
    type: object
    properties:
      request:
        $ref: '#/definitions/Request'
        example:
          to: SunbirdNotif
          type: fcm
          data:
            title: Announcement!!
            notifType: announcement
            summary: New announcement from rootOrg
            body: www.staging-sunbird.org/new/announcement
    required:
    - request
  Request:
    title: Request
    example:
      to: SunbirdNotif
      type: fcm
      data:
        title: Announcement!!
        notifType: announcement
        summary: New announcement from rootOrg
        body: www.staging-sunbird.org/new/announcement
    type: object
    properties:
      to:
        description: ''
        example: SunbirdNotif
        type: string
      type:
        description: ''
        example: fcm
        type: string
      data:
        $ref: '#/definitions/Data'
        example:
          title: Announcement!!
          notifType: announcement
          summary: New announcement from rootOrg
          body: www.staging-sunbird.org/new/announcement
    required:
    - to
    - type
    - data
  Data:
    title: Data
    example:
      title: Announcement!!
      notifType: announcement
      summary: New announcement from rootOrg
      body: www.staging-sunbird.org/new/announcement
    type: object
    properties:
      title:
        description: ''
        example: Announcement!!
        type: string
      notifType:
        description: ''
        example: announcement
        type: string
      summary:
        description: ''
        example: New announcement from rootOrg
        type: string
      body:
        description: ''
        example: www.staging-sunbird.org/new/announcement
        type: string
    required:
    - title
    - notifType
    - summary
    - body
