swagger: '2.0'
info:
  version: '1.0'
  title: Master Key APIs
  description: 'TODO: Add Description'
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: example.com
basePath: /data/v1/client
securityDefinitions:
  auth:
    type: oauth2
    flow: implicit
    authorizationUrl: http://example.com/data/v1/client
    scopes: {}
    x-skip-client-authentication: false
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /key/update:
    patch:
      description: ''
      summary: Update key
      operationId: KeyUpdatePatch
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/UpdateKeyrequest'
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: ts
        in: header
        required: true
        type: string
        description: ''
      - name: X-msgid
        in: header
        required: true
        type: string
        description: ''
      - name: x-authenticated-client-id
        in: header
        required: true
        type: string
        description: ''
      - name: x-authenticated-client-token
        in: header
        required: true
        type: string
        description: ''
      - name: Authorization
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security:
      - auth: []
      x-unitTests:
      - request:
          method: PATCH
          uri: /key/update
          headers:
            Content-Type: application/json
            ts: 2017-05-25 10:18:56:578+0530
            X-msgid: 8e27cbf5-e299-43b0-bca7-8347f7e5abcf
            x-authenticated-client-id: {{client-id}}
            x-authenticated-client-token: {{client-token}}
            Authorization: Bearer {{api-key}}
          body: >-
            {
                "request":{
                "channel":"ROOT_ORG"
                }
            }
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Update key
        x-testDescription: ''
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /key/read/{clientid}:
    get:
      description: ''
      summary: Get key
      operationId: KeyReadByClientidGet
      produces:
      - application/json
      parameters:
      - name: type
        in: query
        required: true
        type: string
        description: ''
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: ts
        in: header
        required: true
        type: string
        description: ''
      - name: X-msgid
        in: header
        required: true
        type: string
        description: ''
      - name: Authorization
        in: header
        required: true
        type: string
        description: ''
      - name: clientid
        in: path
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security:
      - auth: []
      x-unitTests: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /register:
    post:
      description: ''
      summary: Register client
      operationId: RegisterPost
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/RegisterClientrequest'
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: ts
        in: header
        required: true
        type: string
        description: ''
      - name: X-msgid
        in: header
        required: true
        type: string
        description: ''
      - name: Authorization
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
      security:
      - auth: []
      x-unitTests:
      - request:
          method: POST
          uri: /register
          headers:
            Content-Type: application/json
            ts: 2017-05-25 10:18:56:578+0530
            X-msgid: 8e27cbf5-e299-43b0-bca7-8347f7e5abcf
            Authorization: Bearer {{api-key}}
          body: "{\"request\": { \n      \"clientName\":\"dev_testing\"\n  }\n}"
        expectedResponse:
          x-allowExtraHeaders: true
          x-bodyMatchMode: NONE
          x-arrayOrderedMatching: false
          x-arrayCheckCount: false
          x-matchResponseSchema: true
          headers: {}
        x-testShouldPass: true
        x-testEnabled: true
        x-testName: Register client
        x-testDescription: ''
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
definitions:
  UpdateKeyrequest:
    title: Update keyRequest
    example:
      request:
        channel: ROOT_ORG
    type: object
    properties:
      request:
        $ref: '#/definitions/Request'
        example:
          channel: ROOT_ORG
    required:
    - request
  Request:
    title: Request
    example:
      channel: ROOT_ORG
    type: object
    properties:
      channel:
        description: ''
        example: ROOT_ORG
        type: string
    required:
    - channel
  RegisterClientrequest:
    title: Register clientRequest
    example:
      request:
        clientName: dev_testing
    type: object
    properties:
      request:
        $ref: '#/definitions/Request3'
        example:
          clientName: dev_testing
    required:
    - request
  Request3:
    title: Request3
    example:
      clientName: dev_testing
    type: object
    properties:
      clientName:
        description: ''
        example: dev_testing
        type: string
    required:
    - clientName
